### PR TITLE
demo: how to use pug-plugin

### PR DESCRIPTION
**Pull request by webdiscus**
Hello Allahyar,

I am author of the `@webdiscus/pug-loader`, that you use in this project.
I want  demonstrate you a better and easy way to use Pug.
Please see my commentaries in code.

P.S. this pull request is for demonstration how to use the pug-plugin. You can ignore it.

Bests,
Dimitri

### CODE REVIEW

**Comment by allahyar** [comment]
Hello Dimitri,

It was on time, thank you.

**Comment by webdiscus** [comment]
Hello Allahyar,

add in the `tailwind.config.js` supports for Pug extension:
```js
content: ["./src/**/*.{pug,html,js}"],
```

then it's works.

**Comment by allahyar** [comment]
Hello Dimitri,

I noticed a problem load some local images, If the file exists.

`[pug-plugin] Can't resolve the file .../assets/images/google-icon.png`  

thank you for your help.

**Comment by webdiscus** [comment]
>  [pug-plugin] Can't resolve the file .../assets/images/google-icon.png

Hello Allahyar,

possible your relative (by Pug file) path  is wrong, or you has write error in path: it begin with 3 dots `.../`, but must be with 2 dots `../`

Tip: use webpack aliases to avoid relative paths in templates.

_webpack config_
```js
{
  {
    resolve: {
      alias: {
        Views: path.join(__dirname, 'src/views/'),
        Images: path.join(__dirname, 'src/assets/images/'),
        Fonts: path.join(__dirname, 'src/assets/fonts/'),
        Styles: path.join(__dirname, 'src/assets/styles/'),
        Scripts: path.join(__dirname, 'src/assets/scripts/'),
      },
    },
  },
 ...
}
```

Then use aliases in Pug:

```pug
//- alias Views
include Views/mixins/my-mixin

//- alias Styles
link(rel="stylesheet", href=require('Styles/main.scss'))

//- alias Scripts
script(src=require('Scripts/main.js'))

//- alias Images
img(src=require('Images/google-icon.png))
```

**Comment by allahyar** [comment]
3 dots to shorten the file path , I used the aliases but the error was not fixed

**Comment by webdiscus** [comment]
@allahyar 

then check please the webpack rule for images.
The rule for images must have the `type: 'asset/resource'`.

For example:
```js
{
  module: {
    rules: [
      {
        test: /\.(png|svg|jpe?g|webp)$/i,
        type: 'asset/resource', // this is very important
        generator: {
          // output filename of images
          filename: 'assets/img/[name].[hash:8][ext]',
        },
      },
    ...
    ],
  },
}
```

**Pull request merged**
